services:
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network
    ports:
      - "8081:8081"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo:/data/db
    networks:
      - mongo-compose-network

  app:
    container_name: push-api
    image: push
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - api_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./.docker/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - api_network

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - api_network

networks:
  api_network:
  mongo-compose-network:
    driver: bridge
