@baseUrl = http://localhost:3001/api/v1

# @name ping
GET {{baseUrl}}/welcome
Content-Type: application/json

###

# @name create_communication_channel
POST {{baseUrl}}/communication-channels
Content-Type: application/json

{
    "name": "Email",
    "description": "Email dispatcher"
}