basePath: /api/v1
definitions:
  notification_entity.Notification:
    properties:
      communication_channel_id:
        type: string
      created_at:
        type: string
      date:
        type: string
      destination:
        type: string
      id:
        type: string
      retries:
        type: integer
      status:
        type: string
    required:
    - communication_channel_id
    - created_at
    - date
    - destination
    - id
    - status
    type: object
  rest.Response:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
  v1.CancelNotificationResponse:
    properties:
      data:
        $ref: '#/definitions/notification_entity.Notification'
      message:
        type: string
    type: object
  v1.CreateCommunicationChannelRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  v1.GetNotificationResponse:
    properties:
      data:
        $ref: '#/definitions/notification_entity.Notification'
      message:
        type: string
    type: object
  v1.ScheduleNotificationRequest:
    properties:
      communication_channel_id:
        type: string
      destination:
        type: string
      raw_date:
        type: string
    required:
    - communication_channel_id
    - destination
    - raw_date
    type: object
host: localhost:3000
info:
  contact:
    email: gustavodiasa2121@gmail.com
    name: Gustavo Dias
    url: https://github.com/charmingruby
  description: This is the push for new Go APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: push
  version: "1.0"
paths:
  /communication-channels:
    post:
      consumes:
      - application/json
      description: Creates a communication channel
      parameters:
      - description: Create Communication Channel Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.CreateCommunicationChannelRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rest.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/rest.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/rest.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Response'
      summary: Creates a communication channel
      tags:
      - Communication Channel
  /notifications:
    post:
      consumes:
      - application/json
      description: Schedules a notification
      parameters:
      - description: Schedule Notification Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.ScheduleNotificationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rest.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/rest.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Response'
      summary: Schedules a notification
      tags:
      - Notifications
  /notifications/{id}:
    get:
      consumes:
      - application/json
      description: Gets a notification
      parameters:
      - description: Get Notification Payload
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetNotificationResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Response'
      summary: Gets a notification
      tags:
      - Notifications
  /notifications/{id}/cancel:
    patch:
      consumes:
      - application/json
      description: Cancel notification
      parameters:
      - description: Cancel Notification Payload
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CancelNotificationResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/rest.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Response'
      summary: Cancel notification
      tags:
      - Notifications
  /welcome:
    get:
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Response'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
